Foreground yes
LocalSocket /run/clamav/clamd.sock
LocalSocketMode 660
FixStaleSocket yes
StreamMaxLength 8M
MaxScanSize 8M
MaxFileSize 8M
MaxThreads 1
ReadTimeout 90
CommandReadTimeout 5
SendBufTimeout 90
